[package]
edition.workspace = true
license.workspace = true
name = "codex-utils-path"
version.workspace = true

[lints]
workspace = true

[dependencies]
codex-utils-absolute-path = { workspace = true }
dunce = { workspace = true }
tempfile = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_UI_Shell",
] }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }

[lib]
doctest = false
